# Generated by Django 3.1.6 on 2021-02-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210225_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deparment',
            new_name='Department',
        ),
    ]
