# Generated by Django 3.1.6 on 2021-02-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20210204_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(max_length=3)),
                ('currency_rate', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
            ],
        ),
    ]
