# Generated by Django 3.1.6 on 2021-02-05 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_currencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='currency_rate',
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_rate', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('currency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.currencies')),
            ],
        ),
    ]
