# Generated by Django 3.1.6 on 2021-02-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20210205_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currencies',
            new_name='Currency',
        ),
        migrations.RenameModel(
            old_name='Rates',
            new_name='Rate',
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
