# Generated by Django 3.1.6 on 2021-02-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_auto_20210205_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_name',
            field=models.CharField(max_length=100),
        ),
    ]
