# Generated by Django 3.1.6 on 2021-02-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_auto_20210208_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier_person'),
        ),
    ]
