# Generated by Django 3.1.6 on 2021-02-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_auto_20210208_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.ManyToManyField(to='suppliers.Supplier_person'),
        ),
    ]
