# Generated by Django 3.1.6 on 2021-02-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_auto_20210208_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier_person',
        ),
    ]
