# Generated by Django 3.1.6 on 2021-02-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0017_auto_20210208_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Supplier_person',
        ),
    ]
