# Generated by Django 3.1.6 on 2021-02-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0021_product_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier_person',
            new_name='Contact_person',
        ),
    ]
