# Generated by Django 3.1.6 on 2021-02-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0022_auto_20210208_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_person',
            old_name='Job_type',
            new_name='Job_title',
        ),
        migrations.AddField(
            model_name='contact_person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
