# Generated by Django 3.1.6 on 2021-02-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0023_auto_20210208_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_person',
            new_name='ContactPerson',
        ),
    ]
