# Generated by Django 3.1.6 on 2021-02-15 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('suppliers', '0024_auto_20210208_1939'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=200)),
                ('customer_last_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('Agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.currency')),
                ('sales_man', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
