# Generated by Django 3.1.6 on 2021-02-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='projects_files'),
        ),
    ]
