# Generated by Django 3.1.6 on 2021-02-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
