# Generated by Django 3.1.6 on 2021-02-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0024_auto_20210208_1939'),
        ('tasks', '0005_auto_20210218_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgressStatus',
            fields=[
                ('progress_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('progress_status_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='employee',
            new_name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='create_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.currency'),
        ),
        migrations.AddField(
            model_name='task',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='on_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='rest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskprogressstatus'),
        ),
    ]
